#!/bin/bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_bat() {
  if [[ -e /sys/class/power_supply/BAT0/status ]]; then
    bat_status=$(< /sys/class/power_supply/BAT0/status)
    if [[ -e /sys/class/power_supply/BAT0/capacity ]]; then
      bat_capacity=$(< /sys/class/power_supply/BAT0/capacity)
      bat="$bat_status $bat_capacity%"
    else
      bat="$bat_status (capacity not available)"
    fi
  fi
}

update_vol() {
  vol="$(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
}

# Display function
display() {
  status=""
  [[ -n "$bat" ]] && status+="$bat "
  [[ -n "$vol" ]] && status+="$vol "
  [[ -n "$time" ]] && status+="$time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN"
trap "update_bat; display" "RTMIN+1"

# Initial updates
update_vol

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 60)) in
    0) update_bat;;
    [1-5]) 
      update_time
      update_vol
      display
      ;;
  esac
done

