#!/bin/bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_vol() {
  vol="$(pactl list sinks | awk '/Volume:/ {print $5}' | awk 'NR==3' | tr -d '%')%"
}

# Display function
display() {
  status=""
  [[ -n "$vol" ]] && status+="$vol "
  [[ -n "$time" ]] && status+="$time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN+1"

# Initial updates
update_vol

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 60)) in
    [1-5]) 
      update_time
      update_vol
      display
      ;;
  esac
done

